### PR TITLE
adding bootstrap and experimentation folders

### PR DESCRIPTION
**Pull request by davelanglois-ssc**
adding bootstrap folder and experimentation environment to be consistent with documentation

### CODE REVIEW

**Review by alaincormier-ssc — DISMISSED** [review]

**Review by stephanemillaire-ssc — COMMENTED** [review]
Should we also add validate-yaml to .azure-pipelines?

**Review by stephanemillaire-ssc — COMMENTED** [review]
Should we also add validate-yaml to .azure-pipelines?

**Comment by alaincormier-ssc** [comment]
> Should we also add validate-yaml to .azure-pipelines?

actually, we should probably remove version-tagging.yaml from the template...I think they should be added manually based on what's in the tools version at the time of cloning? (that way we don't have to manage those yaml files here)

**Comment by davelanglois-ssc** [comment]
> > Should we also add validate-yaml to .azure-pipelines?
> 
> actually, we should probably remove version-tagging.yaml from the template...I think they should be added manually based on what's in the tools version at the time of cloning? (that way we don't have to manage those yaml files here)

yep, I agree

**Review by stephanemillaire-ssc — APPROVED** [review]
lgtm

**Review by alaincormier-ssc — APPROVED** [review]

**Pull request merged**
